'use client';

import { Close } from '../icons';
import { DEFAULT_TASK, TaskPayload } from '@/lib/types';
import { FormState } from '@/lib/hooks/useFormState';
import { createTask, updateTask } from '@/lib/actions/tasks';
import { useReducer } from 'react';
import { useForm } from 'react-hook-form';
import { useCourseData } from '../providers';
import styles from './form.module.css';

const TEST_USER = '0';

// TODO: singular date doesn't seem like it will work with optional time requirement, probably store dueDate (required) and dueTime (optional)

type TaskFormProps = {
    state: FormState<TaskPayload>;
    onCloseClick?: () => void;
};

export default function TaskForm(props: TaskFormProps) {
    // form data managed by useForm hook
    const { register, handleSubmit } = useForm<TaskPayload>({
        values: props.state.mode === 'update' ? props.state.data : DEFAULT_TASK,
    });

    // should time be included for this task?
    const [includeTime, toggleIncludeTime] = useReducer((curr) => !curr, true);

    // reference all courses to link a task to a course
    const courses = useCourseData().data;

    if (props.state.mode === 'closed') {
        // return early if closed and render nothing
        return;
    }

    const title = props.state.mode === 'create' ? 'Add Task' : 'Modify Task';

    function onSubmit(data: Partial<TaskPayload>) {
        // common task data used when either creating or updating
        const partialTask = {
            // required task fields
            name: data.name!,
            due: data.due!,
            // optional task fields
            description: data.description ?? '',
            subtasks: data.subtasks ?? [],
            courseId: (data.courseId === '' ? null : data.courseId) ?? null,
        } satisfies Partial<TaskPayload>;

        console.log(partialTask);

        switch (props.state.mode) {
            case 'closed':
                console.error('Task form is being submitted in closed state');
                break;

            case 'create':
                createTask({
                    ...partialTask,
                    id: '', // id will be auto-generated by prisma
                    completed: false,
                    userId: TEST_USER,
                });
                break;

            case 'update':
                const initial = props.state.data;
                updateTask({
                    ...partialTask,
                    id: initial.id,
                    completed: initial.completed,
                    userId: initial.userId,
                });
                break;
        }

        // close the form after submitting
        props.onCloseClick && props.onCloseClick();
    }

    return (
        <div className={styles.fillPage}>
            <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
                <div className={styles.formHeader}>
                    <h1>{title}</h1>

                    <button
                        className={styles.closeButton}
                        type='button'
                        onClick={props.onCloseClick}
                    >
                        <Close size={30} color='white' />
                    </button>
                </div>

                <hr />

                <div className={styles.formSection}>
                    <div className={styles.fieldContainer}>
                        <label htmlFor='name'>
                            <p>Name</p>
                        </label>
                        <input
                            type='text'
                            id='name'
                            {...register('name', { required: true })}
                        />
                    </div>

                    <div className={styles.fieldContainer}>
                        <label htmlFor='course'>
                            <p>Course</p>
                        </label>

                        <select id='course' {...register('courseId')}>
                            {/* IMPORTANT: remember to convert (null <=> '') */}
                            <option value=''>None</option>

                            {courses.map((c) => (
                                <option
                                    key={c.id}
                                    value={c.id}
                                    style={{ color: c.color }}
                                >
                                    {c.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div className={styles.fieldContainer}>
                        <label htmlFor='due'>
                            <p>Due</p>
                        </label>

                        <input
                            type='date'
                            id='due'
                            {...(register('due'), { required: true })}
                        />

                        <div className={styles.timeContainer}>
                            {/* TODO: fix layout shift when showing or hiding time */}
                            <input
                                type='checkbox'
                                id='dueTime'
                                checked={includeTime}
                                onChange={toggleIncludeTime}
                            />

                            <label htmlFor='dueTime'>
                                <p>Include Time </p>
                            </label>

                            <input
                                type='time'
                                defaultValue={'23:59'}
                                hidden={!includeTime}
                            />
                        </div>
                    </div>
                </div>

                <hr />

                {/* TODO: subtasks */}
                <div className={styles.formSection}>
                    <p>=== Subtasks here ===</p>
                </div>

                <hr />

                <div className={styles.formSection}>
                    <div className={styles.fieldContainer}>
                        <label htmlFor='description'>
                            <p>Description (optional)</p>
                        </label>

                        <textarea
                            id='description'
                            {...register('description')}
                            rows={4}
                        />
                    </div>
                </div>

                <hr />

                <button className={styles.submit} type='submit'>
                    <h3>Submit</h3>
                </button>
            </form>
        </div>
    );
}
